use std::{env, fs, path::Path};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let check = match env::args().skip(1).collect::<Vec<_>>().as_slice() {
        [] => false,
        [arg] if arg == "--check" => true,
        _ => return Err("usage: generate-bindings [--check]".into()),
    };
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    // Use the same rustfmt configuration regardless of the caller's directory.
    env::set_current_dir(&root)?;
    let checked_in = root.join("src/bindings.rs");
    let output = root.join("tools/bindings/target/bindings.rs");
    fs::create_dir_all(output.parent().unwrap())?;
    windows_bindgen::Bindgen::new().output(&output).flat().filter_file(root.join("tools/bindings/filter.txt")).write();
    let generated = format!(
        "// Generated by windows-bindgen 0.100.0. Do not edit.\n\
         // Regenerate: cargo run --locked --manifest-path tools/bindings/Cargo.toml\n\n{}",
        fs::read_to_string(&output)?
    );
    if check {
        if fs::read(&checked_in)? != generated.as_bytes() {
            return Err("src/bindings.rs is stale; run the regeneration command in its header".into());
        }
        println!("Windows bindings are up to date.");
    } else {
        fs::write(checked_in, generated)?;
    }
    Ok(())
}
